### ISSUE TITLE
node-sass

### ISSUE THREAD

**Issue by jdgamble555** [Oli8/spaper#25]
Node a big deal, but `node-sass` should be added to this package's dependencies as it is a requirement to run in svelte-kit.  At the very least, it should be added to a svelte-kit instruction guide.

J

**Comment by Oli8** [comment]
Yep, node-sass should not have been needed as dependency as the scss gets correctly converted to css on package generation.
Unfortunately the `lang="scss"` was kept which made it crash without node-sass.
This is now fixed in newer svelte-kit version, so from the next spaper version on, node-sass won't be required anymore.

**Comment by Oli8** [comment]
Fixed in v0.3.6
